use aiken/builtin.{append_bytearray}
use aiken/crypto.{blake2b_256}
use aiken/crypto/bls12_381/scalar.{from_bytes}
use cardano/assets.{PolicyId, has_nft_strict}
use cardano/transaction.{Transaction}
use proof_verifier.{verifier}

type Redeemer =
  (ByteArray, ByteArray)

validator halo2 {
  mint(redeemer: Redeemer, policy_id: PolicyId, transaction: Transaction) {
    let (proof, instance_1) = redeemer

    let for_hashing =
      append_bytearray(proof, instance_1)

    let expected_nft_name = blake2b_256(for_hashing)

    expect has_nft_strict(transaction.mint, policy_id, expected_nft_name)

    verifier(
      proof,
      from_bytes(instance_1),
    )
  }

  else(_) {
    fail
  }
}
